package/udev: fix CFLAGS for udev extras
If the udev extras are built without large file support in uClibc,
I get the following error:

 build_powerpc/staging_dir/usr/bin/powerpc-linux-uclibc-gcc -c -g -Wall
 -pipe -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -Wstrict-prototypes
 -Wsign-compare -Wshadow -Wchar-subscripts -Wmissing-declarations
 -Wnested-externs -Wpointer-arith -Wcast-align -Wsign-compare
 -Wmissing-prototypes -Os ext.c -o ext.o
 In file included from build_powerpc/staging_dir/usr/include/stdio.h:28,
 from ext.c:19:
 build_powerpc/staging_dir/usr/include/features.h:382:4: error:
 #error It appears you have defined _FILE_OFFSET_BITS=64. Unfortunately,
 uClibc was built without large file support enabled.

Although the base udev package builds correctly, the extras pacakges
don't adjust their CFLAGS depending on BR2_LARGEFILE.

This change adds the required CFLAGS modifications to make the
extras build.

Signed-off-by: Jeremy Kerr <jk@ozlabs.org>