mplayer: add -fomit-frame-pointer for i386
This seems to be required to compile some of the inline asm.

This solves the following compiler errors:
h264.c: In function 'decode_cabac_residual':
h264.c:6158: warning: passing argument 4 of 'decode_significance_8x8_x86' discards qualifiers from pointer target type
cabac.h: In function 'get_cabac_noinline':
cabac.h:513: error: can't find a register in class 'GENERAL_REGS' while reloading 'asm'
cabac.h:513: error: 'asm' operand has impossible constraints

While searching several weeks ago, I hit the following URL, which
unfortunately currently doesn't seem to work anymore and I can't
remember what the bug was about.

Also see http://bugs.uclibc.org/view.php?id=4604

Signed-off-by: Markus Heidelberg <markus.heidelberg@web.de>